apiVersion: v1
kind: PersistentVolume
metadata:
  name: kasten-pv
  namespace: kasten-io
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs
  awsElasticBlockStore:
    volumeID: vol-06c2f87c1d9248589
    fsType: ext4

